import Link from 'next/link';
import Navbar from '../components/Navbar.js';
import Footer from '../components/Footer.js';
import HomeExplorer from '../components/HomeExplorer.js';
import { getDirectory } from '../lib/directory.js';
import { GUIDES } from '../lib/guides.js';
import { pageMetadata } from '../lib/seo.js';
export const metadata = pageMetadata('Todo Lima | Encuentra y compara negocios y servicios en Lima', 'Explora negocios por categoría y distrito. Compara ubicación, canales de contacto y guías prácticas para elegir servicios en Lima.', '/');
export default function HomePage() {
  const categories = getDirectory().map(c => ({ ...c.meta, count: c.businesses.length }));
  return <><Navbar /><main id="contenido" className="flex-grow"><section className="relative bg-slate-950 text-white overflow-hidden"><img src="/images/lima-hero.jpg" alt="" fetchPriority="high" width="1920" height="1080" className="absolute inset-0 w-full h-full object-cover opacity-25" /><div className="relative max-w-7xl mx-auto px-5 py-20 sm:py-28"><p className="text-sky-300 text-sm font-semibold mb-5">LIMA, A TU ALCANCE</p><h1 className="text-4xl sm:text-6xl font-black leading-tight max-w-3xl">Encuentra lo que necesitas.<br /><span className="text-sky-300">Elige con información.</span></h1><p className="mt-6 text-lg text-slate-300 max-w-2xl leading-relaxed">Negocios, especialistas y servicios de Lima en un solo lugar. Explora opciones, compara ubicaciones y consulta directamente con cada proveedor.</p><div className="flex flex-wrap gap-4 mt-8"><a className="rounded-xl bg-sky-500 px-6 py-3.5 font-bold text-white" href="#directorios">Explorar {categories.length} categorías →</a><Link className="rounded-xl border border-slate-500 px-6 py-3.5 font-semibold" href="/guias">Guías para elegir</Link></div><div className="flex flex-wrap gap-5 mt-10 text-sm text-slate-300"><span>Sin registro para consultar</span><span>Fuentes visibles</span><span>Contacto sin intermediación</span></div></div></section>
    <HomeExplorer categories={categories} />
    <section className="max-w-7xl mx-auto px-5 py-12"><div className="flex flex-wrap items-center justify-between gap-4 mb-7"><div><p className="text-sky-600 font-semibold text-sm mb-2">ANTES DE CONTRATAR</p><h2 className="text-3xl font-black">Haz mejores preguntas</h2></div><Link href="/guias" className="text-sky-600 font-bold">Todas las guías →</Link></div><div className="grid md:grid-cols-3 gap-5">{GUIDES.slice(0, 3).map(g => <Link className="editorial-card" key={g.slug} href={`/guias/${g.slug}`}><h3 className="text-xl font-bold">{g.title}</h3><p className="text-slate-500 mt-4">{g.description}</p><span className="text-sky-600 font-semibold block mt-5">Leer checklist →</span></Link>)}</div></section>
    <section className="max-w-7xl mx-auto px-5 py-12"><div className="grid md:grid-cols-3 gap-5">{[['Explora por rubro', 'Encuentra opciones para tu servicio y consulta su ubicación.'], ['Compara con contexto', 'Revisa fuentes y guías; confirma precios y condiciones directamente.'], ['Contacta al proveedor', 'Utiliza el teléfono, mapa o web disponible en cada ficha.']].map(([title, text]) => <div className="editorial-card" key={title}><h2 className="text-xl font-bold mb-3">{title}</h2><p>{text}</p></div>)}</div><p className="mt-6 text-sm text-slate-500">La inclusión no certifica al proveedor ni garantiza disponibilidad. <Link className="underline" href="/metodologia">Conoce nuestra metodología</Link>.</p></section>
    <section className="max-w-7xl mx-auto px-5 py-12"><div className="rounded-3xl bg-slate-950 text-white p-8 sm:p-12 flex flex-col md:flex-row gap-6 items-start justify-between"><div><h2 className="text-3xl font-bold">¿Tu negocio está en Lima?</h2><p className="text-slate-300 mt-4 max-w-xl">Solicita la revisión de tu ficha y presenta información que ayude a tus próximos clientes a encontrarte.</p></div><Link className="rounded-xl px-5 py-3 bg-sky-500 font-semibold shrink-0" href="/para-negocios">Conoce cómo participar →</Link></div></section>
  </main><Footer /></>;
}
