export const BLOG_CATEGORIES = [
  ['historia-de-lima', 'Historia de Lima'], ['cultura-y-tradiciones', 'Cultura y tradiciones'],
  ['gastronomia-limena', 'Gastronomía limeña'], ['lugares-y-patrimonio', 'Lugares y patrimonio'],
  ['planes-y-bienestar', 'Planes y bienestar'], ['barrios-y-distritos', 'Barrios y distritos'],
  ['vida-practica', 'Vida práctica en Lima'], ['negocios-locales', 'Negocios e historias locales']
].map(([slug, name]) => ({ slug, name }));
export const BLOG_TAGS = [['centro-historico','Centro Histórico'],['patrimonio','Patrimonio'],['cercado-de-lima','Cercado de Lima'],['negocios-de-barrio','Negocios de barrio'],['servicios-a-domicilio','Servicios a domicilio']].map(([slug,name]) => ({slug,name}));
export const BLOG_IMAGES = {"blog-centro-portada":{"src":"/images/editorial/blog-centro-portada.webp","alt":"Ilustración del patrimonio urbano del Centro Histórico de Lima.","srcSet":"/images/editorial/blog-centro-portada-480.webp 480w, /images/editorial/blog-centro-portada-768.webp 768w, /images/editorial/blog-centro-portada.webp 1440w"},"blog-centro-patrimonio":{"src":"/images/editorial/blog-centro-patrimonio.webp","alt":"Interpretación artística de balcones y arquitectura limeña.","srcSet":"/images/editorial/blog-centro-patrimonio-480.webp 480w, /images/editorial/blog-centro-patrimonio-768.webp 768w, /images/editorial/blog-centro-patrimonio.webp 1440w"},"blog-centro-recorrido":{"src":"/images/editorial/blog-centro-recorrido.webp","alt":"Ilustración de personas preparando un paseo cultural.","srcSet":"/images/editorial/blog-centro-recorrido-480.webp 480w, /images/editorial/blog-centro-recorrido-768.webp 768w, /images/editorial/blog-centro-recorrido.webp 1440w"},"blog-negocio-portada":{"src":"/images/editorial/blog-negocio-portada.webp","alt":"Personas comparan información de un negocio antes de contactarlo.","srcSet":"/images/editorial/blog-negocio-portada-480.webp 480w, /images/editorial/blog-negocio-portada-768.webp 768w, /images/editorial/blog-negocio-portada.webp 1440w"},"blog-negocio-cobertura":{"src":"/images/editorial/blog-negocio-cobertura.webp","alt":"Clienta consulta la cobertura del servicio por teléfono.","srcSet":"/images/editorial/blog-negocio-cobertura-480.webp 480w, /images/editorial/blog-negocio-cobertura-768.webp 768w, /images/editorial/blog-negocio-cobertura.webp 1440w"},"blog-negocio-condiciones":{"src":"/images/editorial/blog-negocio-condiciones.webp","alt":"Documentos y notas para comparar las condiciones de un servicio.","srcSet":"/images/editorial/blog-negocio-condiciones-480.webp 480w, /images/editorial/blog-negocio-condiciones-768.webp 768w, /images/editorial/blog-negocio-condiciones.webp 1440w"}};
export function categoryName(slug) { return BLOG_CATEGORIES.find(c => c.slug === slug)?.name; }
