// Explicit service scope and buying criteria. These describe what to ask about,
// not capabilities or credentials attributed to individual listed businesses.
export const CATEGORY_DETAILS = {
  doctores: ['consultas generales, especialidades médicas y modalidades de atención', 'especialidad, colegiatura y modalidad de consulta'],
  dentistas: ['evaluación odontológica, limpieza y tratamientos dentales', 'diagnóstico, plan de tratamiento y presupuesto por etapas'],
  psicologos: ['consulta psicológica, terapia individual y atención de pareja', 'formación, enfoque de trabajo y condiciones de confidencialidad'],
  pediatras: ['consultas pediátricas y seguimiento infantil', 'especialidad, edad atendida y organización de la consulta'],
  dermatologos: ['consulta de piel y evaluación dermatológica', 'especialidad y diferencia entre evaluación clínica y procedimientos estéticos'],
  veterinarias: ['consultas para mascotas y servicios veterinarios', 'especies atendidas, horarios y disponibilidad real fuera de horario'],
  fisioterapia: ['evaluación funcional y rehabilitación física', 'profesional responsable, evaluación inicial y objetivos del plan'],
  nutricionistas: ['evaluación nutricional y seguimiento de hábitos', 'formación, evaluación inicial y alcance del seguimiento'],
  oftalmologos: ['consultas y evaluación de salud ocular', 'especialidad, exámenes incluidos y condiciones de seguimiento'],
  ginecologos: ['consultas ginecológicas y seguimiento de salud de la mujer', 'especialidad, privacidad y exámenes incluidos'],
  cerrajeros: ['apertura, cambio de cerraduras y duplicado de llaves', 'costo de desplazamiento, autorización de acceso y piezas incluidas'],
  gasfiteros: ['fugas de agua, desatoros e instalaciones sanitarias', 'diagnóstico, materiales, visita y condiciones de garantía'],
  electricistas: ['diagnóstico eléctrico y mantenimiento de instalaciones', 'experiencia para el tipo de instalación y medidas de seguridad'],
  pintores: ['pintura de interiores, exteriores y preparación de superficies', 'área medida, preparación, número de manos y materiales'],
  fumigacion: ['control de plagas y tratamientos preventivos', 'plaga identificada, productos, preparación y tiempo de reingreso'],
  mudanzas: ['traslado de muebles, embalaje y transporte de enseres', 'inventario, pisos, ascensor, embalaje y responsabilidad por daños'],
  'aire-acondicionado': ['instalación, limpieza y mantenimiento de equipos', 'capacidad del equipo, repuestos y alcance de la instalación'],
  'reparacion-lavadoras': ['diagnóstico y reparación de lavadoras', 'marca, modelo, diagnóstico y garantía de repuestos'],
  'reparacion-refrigeradoras': ['diagnóstico y reparación de refrigeradoras', 'modelo, costo de diagnóstico y piezas propuestas'],
  vidrierias: ['vidrios, espejos, ventanas y mamparas', 'medidas, espesor, tipo de vidrio e instalación'],
  carpinteros: ['muebles a medida y reparación de carpintería', 'material, medidas, herrajes, acabados y plazo de entrega'],
  abogados: ['consulta legal y asesoría por especialidad', 'colegiatura, experiencia en la materia y alcance de honorarios'],
  notarias: ['trámites notariales, certificaciones y escrituras', 'requisitos oficiales del trámite, citas y costos desglosados'],
  contadores: ['contabilidad, declaraciones y asesoría tributaria', 'alcance mensual, documentación y responsabilidades del servicio'],
  'agentes-inmobiliarios': ['intermediación para venta y alquiler de propiedades', 'registro aplicable, comisión y condiciones del encargo'],
  'talleres-mecanicos': ['mantenimiento y diagnóstico automotriz', 'marca atendida, diagnóstico, repuestos y orden de trabajo'],
  'car-wash': ['lavado y cuidado exterior e interior del vehículo', 'procedimiento, productos y alcance del paquete'],
  llanterias: ['cambio de neumáticos, parchado y servicios de ruedas', 'medida, fecha de fabricación y servicios incluidos'],
  'auxilio-mecanico': ['asistencia vehicular y traslado con grúa', 'ubicación, tipo de vehículo y costo total del traslado'],
  catering: ['alimentación y atención para eventos', 'invitados, menú, menaje, personal y restricciones alimentarias'],
  'tortas-personalizadas': ['tortas por encargo y diseños para celebraciones', 'porciones, ingredientes, diseño y condiciones de entrega'],
  'fotografia-eventos': ['cobertura fotográfica para eventos', 'horas, entregables, edición y derechos de uso de imágenes'],
  barberias: ['corte de cabello y arreglo de barba', 'servicio incluido, cita y condiciones de higiene'],
  'salones-de-belleza': ['cortes, coloración y peinados', 'evaluación previa, productos y costo según largo del cabello'],
  spas: ['masajes y servicios de bienestar', 'duración, tipo de servicio y condiciones de reserva'],
  'reparacion-celulares': ['diagnóstico y reparación de celulares y tablets', 'modelo, procedencia del repuesto y protección de datos'],
  'reparacion-laptops': ['diagnóstico y mantenimiento de laptops y computadoras', 'respaldo, autorización de cambios y garantía del trabajo'],
  'camaras-de-seguridad': ['instalación y mantenimiento de videovigilancia', 'cobertura, almacenamiento, cableado y acceso a las grabaciones'],
  cevicherias: ['comida marina y platos de ceviche', 'carta vigente, horarios y condiciones de reserva'],
  pollerias: ['pollo a la brasa y platos para compartir', 'porciones, acompañamientos y costo de entrega'],
  chifas: ['cocina peruano-china y menús para compartir', 'carta, tamaño de las porciones y opciones alimentarias'],
  pizzerias: ['pizzas y opciones de consumo en local o entrega', 'tamaño, ingredientes y cobertura de delivery'],
  cafeterias: ['café, desayunos y opciones para una pausa', 'horarios, carta y servicios del local confirmados'],
  florerias: ['arreglos florales y entregas por encargo', 'flores disponibles, sustituciones y ventana de entrega'],
  opticas: ['monturas, lentes y servicios ópticos', 'receta, materiales y garantía de fabricación'],
  lavanderias: ['lavado de prendas y servicios de tintorería', 'tipo de prenda, tratamiento, entrega y política por daños'],
  'escuelas-de-manejo': ['clases de conducción y preparación práctica', 'autorización aplicable, horas efectivas y condiciones del curso'],
  'casas-de-cambio': ['compra y venta de divisas', 'cotización vigente, comisiones y medidas de seguridad'],
  podologos: ['consulta y cuidado de los pies', 'formación, alcance del servicio y derivación cuando sea necesaria'],
  'laboratorios-clinicos': ['análisis y toma de muestras', 'orden, preparación indicada por el profesional y entrega de resultados'],
  traumatologos: ['consultas de traumatología y evaluación de lesiones', 'especialidad, documentación previa y exámenes indicados'],
  'grooming-canino': ['baño y arreglo de mascotas', 'especie, tamaño, manejo y productos utilizados'],
  gimnasios: ['entrenamiento y clases de actividad física', 'horarios, instalaciones y condiciones de membresía'],
  'locales-de-eventos': ['espacios para celebraciones y reuniones', 'capacidad, acceso, horarios y servicios incluidos'],
  'decoracion-de-eventos': ['ambientación y montaje para celebraciones', 'diseño, materiales, montaje y retiro'],
  'alquiler-de-canchas': ['reserva de espacios deportivos', 'duración, iluminación, instalaciones y reglas de cancelación'],
};

export function categoryEditorial(category) {
  const [services, criteria] = CATEGORY_DETAILS[category.slug];
  return {
    description: `Explora opciones de ${category.title.toLowerCase()}. Compara ubicación, información disponible y canales de contacto antes de elegir.`,
    introduction: `Este directorio reúne negocios y profesionales relacionados con ${services}. Utiliza la dirección para ubicar cada opción y consulta al proveedor si atiende tu distrito: la ubicación del local y la cobertura a domicilio pueden ser distintas.`,
    sections: [
      { title: 'Qué comparar antes de elegir', text: `Para este servicio conviene confirmar ${criteria}. Describe tu necesidad de forma concreta y solicita una respuesta por escrito cuando haya un presupuesto o compromiso de entrega. Una calificación en una plataforma externa puede ayudar a explorar opciones, pero no demuestra por sí sola experiencia, habilitación o disponibilidad.` },
      { title: 'Cómo consultar precios y condiciones', text: `Pregunta qué incluye el servicio, qué se cobra por separado y qué condiciones pueden modificar el presupuesto. Confirma la fecha, el lugar de atención y las reglas de cambio o cancelación antes de coordinar. Todo Lima no establece los precios de los negocios ni confirma sus reservas.` },
    ],
    questions: [
      { q: `¿Qué debo preguntar al buscar ${category.title.toLowerCase()}?`, a: `Confirma ${criteria}. Comprueba también el canal de contacto y la disponibilidad directamente con el negocio.` },
      { q: '¿La dirección indica que atienden a domicilio en mi distrito?', a: 'No necesariamente. La dirección corresponde a la información de ubicación recogida. Confirma con cada proveedor su cobertura, costo de desplazamiento y modalidad de atención.' },
      { q: '¿Las valoraciones son reseñas propias de Todo Lima?', a: 'No. Cuando se muestra una valoración, procede de la ficha pública enlazada de Google Maps y puede haber cambiado. Consulta la fuente para revisar las opiniones actuales.' },
    ],
  };
}
