import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { getDirectory, getLocalPages, getProfiles } from '../lib/directory.js';
import { GUIDES } from '../lib/guides.js';
const origin = process.env.SEO_TEST_ORIGIN || 'http://localhost:3000';
const paths = ['/', '/guias', '/metodologia', '/correcciones', '/para-negocios', ...getDirectory().map(c => `/${c.meta.slug}`), ...getLocalPages().map(p => `/${p.category}/${p.slug}`), ...getProfiles().map(p => `/negocios/${p.slug}`), ...GUIDES.map(g => `/guias/${g.slug}`)];
for (let i = 0; i < paths.length; i += 4) await Promise.all(paths.slice(i, i + 4).map(async pathname => {
  const response = await fetch(`${origin}${pathname}`);
  assert.equal(response.status, 200, pathname);
  const html = await response.text();
  const canonicals = html.match(/<link[^>]+rel="canonical"[^>]*>/g) || [];
  assert.equal(canonicals.length, 1, `canonical count: ${pathname}`);
  const canonicalUrl = canonicals[0].match(/href="([^"]+)"/)[1];
  assert.equal(new URL(canonicalUrl).pathname, pathname, `canonical path: ${pathname}`);
  assert.equal(new URL(canonicalUrl).origin, 'https://todolima.com', `canonical host: ${pathname}`);
  assert.equal((html.match(/<h1(?:\s|>)/g) || []).length, 1, `H1: ${pathname}`);
  assert(!html.includes('en menos de 15 Minutos'), `unfounded promise: ${pathname}`);
  for (const script of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs)) JSON.parse(script[1]);
}));
const redirect = await fetch(`${origin}/directorio/dentistas?distrito=Miraflores`, { redirect: 'manual' });
assert.equal(redirect.status, 308);
assert(redirect.headers.get('location').endsWith('/dentistas?distrito=Miraflores'));
assert.equal((await fetch(`${origin}/dentistas?distrito=Miraflores`)).headers.get('x-robots-tag'), 'noindex, follow');
assert.equal((await fetch(`${origin}/admin`)).headers.get('x-robots-tag'), 'noindex, nofollow');
assert.equal((await fetch(`${origin}/unknown-seo-category`)).status, 404);
assert.equal((await fetch(`${origin}/gasfiteros/unknown-district`)).status, 404);
const sitemap = await (await fetch(`${origin}/sitemap.xml`)).text();
assert(!sitemap.includes('/directorio/') && !sitemap.includes('/demo/') && !sitemap.includes('/admin'));
for (const pathname of paths) assert(sitemap.includes(`https://todolima.com${pathname === '/' ? '' : pathname}`), `sitemap: ${pathname}`);
const browser = await chromium.launch();
try {
  const noJS = await browser.newContext({ javaScriptEnabled: false });
  const textPage = await noJS.newPage();
  await textPage.goto(`${origin}/gasfiteros`);
  assert((await textPage.locator('article').count()) >= 5, 'Business listings must render without JavaScript');
  await noJS.close();
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(origin, { waitUntil: 'networkidle' });
  assert.equal(await page.locator('#directorios img').count(), 56, 'Category illustrations restored');
  await page.getByRole('button', { name: 'Salud y bienestar', exact: true }).click();
  assert((await page.locator('#directorios h3').count()) > 0 && (await page.locator('#directorios h3').count()) < 56);
  await page.getByRole('button', { name: 'Limpiar filtros', exact: true }).click();
  await page.getByLabel('Distrito', { exact: true }).selectOption('Miraflores');
  assert((await page.locator('#directorios h3').count()) > 0);
  for (const link of await page.locator('#directorios a').evaluateAll(links => links.map(a => a.getAttribute('href')))) assert(link.includes('distrito=Miraflores'));
  await page.getByRole('button', { name: 'Limpiar filtros', exact: true }).click();
  await page.getByRole('button', { name: 'Letra G', exact: true }).click();
  for (const title of await page.locator('#directorios h3').allTextContents()) assert(title.startsWith('G'));
  await page.getByRole('button', { name: 'Limpiar filtros', exact: true }).click();
  await page.getByLabel('Ordenar categorías').selectOption('za');
  const descending = await page.locator('#directorios h3').allTextContents();
  assert.deepEqual(descending, [...descending].sort((a, b) => b.localeCompare(a, 'es')));
  await page.getByRole('button', { name: 'Limpiar filtros', exact: true }).click();
  assert.equal(await page.locator('#directorios h3').count(), 56);
  await page.screenshot({ path: '.next/seo-home-desktop.png', fullPage: true });
  await page.getByLabel('Buscar categoría', { exact: true }).fill('gasfiteros');
  assert.equal(await page.locator('#directorios h3').count(), 1);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto(origin, { waitUntil: 'networkidle' });
  await page.locator('#directorios a').first().scrollIntoViewIfNeeded();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Home mobile overflow');
  await page.waitForFunction(() => [...document.querySelectorAll('#directorios img')].slice(0, 2).every(img => img.complete && img.naturalWidth > 0));
  await page.locator('#directorios img').first().evaluate(async img => { await img.decode(); await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))); });
  await page.screenshot({ path: '.next/visual-home-mobile.png' });
  await page.getByRole('button', { name: 'Abrir menú' }).click();
  await page.locator('#mobile-menu').getByRole('link', { name: 'Guías', exact: true }).click();
  await page.waitForURL('**/guias');
  assert(await page.getByRole('heading', { name: 'Decide con más información' }).isVisible());
  await page.goto(`${origin}/gasfiteros`, { waitUntil: 'networkidle' });
  await page.screenshot({ path: '.next/visual-category-header-mobile.png' });
  for (const width of [320, 375, 390, 768, 820, 1024, 1280, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    await page.goto(`${origin}/gasfiteros`, { waitUntil: 'domcontentloaded' });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `Horizontal overflow at ${width}px`);
    const selectors = await page.getByTestId('directory-selectors').boundingBox();
    const chips = await page.getByTestId('district-chips').boundingBox();
    assert(selectors && chips, `Directory controls visible at ${width}px`);
    assert(selectors.y >= chips.y + chips.height - 1, `Directory controls overlap at ${width}px`);
    for (const select of await page.getByTestId('directory-selectors').locator('select').all()) {
      const box = await select.boundingBox();
      assert(box && box.x >= 0 && box.x + box.width <= width + 1, `Select outside viewport at ${width}px`);
    }
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel('Buscar negocios por nombre, distrito o dirección').fill('zzzz-nonexistent');
  assert.equal(await page.locator('article').count(), 0);
  await page.getByRole('button', { name: 'Restablecer todos los filtros' }).click();
  assert((await page.locator('article').count()) > 0);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile overflow');
  await page.screenshot({ path: '.next/seo-category-mobile.png', fullPage: true });
  assert.deepEqual(errors, [], 'Browser runtime errors');
} finally { await browser.close(); }
console.log(`SEO smoke passed: ${paths.length} pages, redirects, headers, JSON-LD, sitemap, no-JS listings and mobile interactions.`);
